{
 "title": "Power Utilisation & Solar Array",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "MAX Grid Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "switch.tp_link_smart_plug_992b",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "ac_output_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "AC KW Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "ac_output_power_va" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "  / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "KW Output",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "output_load_watt" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "alias": " ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "output_mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "System Load (VA - 10min AVG)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "output_load_percent" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ "/ 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "Running Cost (Display Period)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "LKR. " } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "ac_output_power_va" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 12/ 1000 * 19" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Load %",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "output_load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "PV Input Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "PV Watts (W)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "pv_input_watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    },
    {
     "alias": "PV Current (A)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "pv_input_current_for_battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "System Watts (In/Out)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Grid Input",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "default",
     "query": "SELECT mean(\"ac_output_power_va\") * 0.9\n FROM \"default\" WHERE (\"device\" = 'voltronic') AND $timeFilter GROUP BY time($interval) fill(linear)",
     "select": [
      [
       { "params": [ "ac_output_power_va" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "ac_output_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "ac_output_power_va" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    },
    {
     "alias": "Inverter Output",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "output_load_watt" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "Box Temperature",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "inverter_heat_sink_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Battery Capacity",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "battery_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "Inverter Current (A) - (Battery Bank Charge/Discharge)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Charge Current",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "battery_charging_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    },
    {
     "alias": "Discharge Current",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "battery_discharge_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "Battery Bank Voltage (V)",
   "type": "timeseries",
   "description": "Assumes 50% Discharge maximum on battery bank - To give approx. 3000 Cycles (8Years on bank)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "🔋 Voltage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "default",
     "query": "SELECT mean(\"battery_voltage\") FROM \"autogen\".\"default\" WHERE (\"device\" = 'voltronic') AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "battery_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "AC KW Consumed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Home - Total KWH",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default",
     "query": "SELECT (median(\"ac_output_power_va\")  / 1000 )* 24 FROM \"autogen\".\"default\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_output_power_va" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Input Current (Amps)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "AC ampere",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "default",
     "query": "SELECT  mean(\"ac_output_power_va\") / mean(\"ac_output_voltage\") FROM \"autogen\".\"default\" WHERE (\"device\" = 'voltronic') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "ac_output_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "ac_output_power_va" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  },
  {
   "title": "Grid Voltage Fluctuations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "⚡ Grid - Voltage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "grid_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Bus Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "PV Votage (V)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "default",
     "select": [
      [
       { "params": [ "bus_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "voltronic" }
     ]
    }
   ]
  }
 ]
}